<?php

namespace org\schema\constants\traits;

trait Organization
{
    const string ORGANIZATIONS = 'organizations' ;

    const string ACCEPTED_PAYMENT_METHOD     = 'acceptedPaymentMethod' ;
    const string ACTIONABLE_FEEDBACK_POLICY  = 'actionableFeedbackPolicy' ;
    const string ADDITIONAL                  = 'additional' ;
    const string AGENT_INTERACTION_STATISTIC = 'agentInteractionStatistic' ;
    const string AGGREGATE_RATING            = 'aggregateRating' ;
    const string ADDRESS                     = 'address' ;
    const string ALUMNI                      = 'alumni' ;
    const string APE                         = 'ape' ;
    const string AREA_SERVED                 = 'areaServed' ;
    const string AWARD                       = 'award' ;
    const string BRAND                       = 'brand' ;
    const string COMPANY_REGISTRATION        = 'companyRegistration' ;
    const string CONTACT_POINT               = 'contactPoint' ;
    const string CORRECTIONS_POLICY          = 'correctionsPolicy' ;
    const string DEPARTMENT                  = 'department' ;
    const string DISSOLUTION_DATE            = 'dissolutionDate' ;
    const string DIVERSITY_POLICY            = 'diversityPolicy' ;
    const string DIVERSITY_STAFFING_REPORT   = 'diversityStaffingReport' ;
    const string EMAIL                       = 'email' ;
    const string EMPLOYEE                    = 'employee' ;
    const string ETHICS_POLICY               = 'ethicsPolicy' ;
    const string FOUNDER                     = 'founder' ;
    const string FOUNDING_DATE               = 'foundingDate' ;
    const string FOUNDING_LOCATION           = 'foundingLocation' ;
    const string FUNDER                      = 'funder' ;
    const string FUNDING                     = 'funding' ;
    const string GLOBAL_LOCATION_NUMBER      = 'globalLocationNumber' ;
    const string HAS_CERTIFICATION           = 'hasCertification' ;
    const string HAS_CREDENTIAL              = 'hasCredential' ;
    const string HAS_GS_1_DIGITAL_LINK       = 'hasGS1DigitalLink' ;
    const string HAS_MEMBER_PROGRAM          = 'hasMemberProgram' ;
    const string HAS_MERCHANT_RETURN_POLICY  = 'hasMerchantReturnPolicy' ;
    const string HAS_OFFER_CATALOG           = 'hasOfferCatalog' ;
    const string HAS_POS                     = 'hasPOS' ;
    const string HAS_SHIPPING_SERVICE        = 'hasShippingService' ;
    const string INTERACTION_STATISTIC       = 'interactionStatistic' ;
    const string ISIC_V4                     = 'isicV4' ;
    const string ISO_6523_CODE               = 'iso6523Code' ;
    const string KEYWORDS                    = 'keywords' ;
    const string KNOWS_ABOUT                 = 'knowsAbout' ;
    const string KNOWS_LANGUAGE              = 'knowsLanguage' ;
    const string LEGAL_ADDRESS               = 'legalAddress' ;
    const string LEGAL_NAME                  = 'legalName' ;
    const string LEGAL_FORM                  = 'legalForm' ;
    const string LEGAL_REPRESENTATIVE        = 'legalRepresentative' ;
    const string LEI_CODE                    = 'leiCode' ;
    const string LOCATION                    = 'location' ;
    const string LOGO                        = 'logo' ;
    const string MAKES_OFFER                 = 'makesOffer' ;
    const string MEMBER                      = 'member' ;
    const string MEMBER_OF                   = 'memberOf' ;
    const string MEMBERS                     = 'members' ;
    const string MOBILE                      = 'mobile' ;
    const string NAICS                       = 'naics' ;
    const string NONPROFIT_STATUS            = 'nonprofitStatus' ;
    const string NUMBER_OF_EMPLOYEES         = 'numberOfEmployees' ;
    const string OWNERSHIP_FUNDING_INFO      = 'ownershipFundingInfo' ;
    const string OWNS                        = 'owns' ;
    const string PARENT_ORGANIZATION         = 'parentOrganization' ;
    const string PRODUCER                    = 'producer' ;
    const string PROVIDER                    = 'provider' ;
    const string PROVIDERS                   = 'providers' ;
    const string PUBLISHER                   = 'publisher' ;
    const string PUBLISHING_PRINCIPLES       = 'publishingPrinciples' ;
    const string REVIEW                      = 'review'     ;
    const string SEEKS                       = 'seeks'     ;
    const string SKILLS                      = 'skills'     ;
    const string SLOGAN                      = 'slogan'     ;
    const string SPONSOR                     = 'sponsor'     ;
    const string SUB_ORGANIZATION            = 'subOrganization' ;
    const string TAX_ID                      = 'taxID' ;
    const string TELEPHONE                   = 'telephone' ;
    const string UNNAMED_SOURCES_POLICY      = 'unnamedSourcesPolicy' ;
    const string VAT_ID                      = 'vatID' ;
}