<?php

namespace org\schema\constants\traits;

trait Person
{
    const string PEOPLE                      = 'people' ;
    const string ADDITIONAL_NAME             = 'additionalName' ;
    const string ADDRESS                     = 'address' ;
    const string AFFILIATION                 = 'affiliation' ;
    const string AGENT_INTERACTION_STATISTIC = 'agentInteractionStatistic' ;
    const string ALUMNI_OF                   = 'alumniOf' ;
    const string AWARD                       = 'award' ;
    const string BIRTH_DATE                  = 'birthDate' ;
    const string BIRTH_PLACE                 = 'birthPlace' ;
    const string BRAND                       = 'brand' ;
    const string CALL_SIGN                   = 'callSign' ;
    const string CHILDREN                    = 'children' ;
    const string COLLEAGUE                   = 'colleague' ;
    const string CONTACT_POINT               = 'contactPoint' ;
    const string DEATH_DATE                  = 'deathDate' ;
    const string DEATH_PLACE                 = 'deathPlace' ;
    const string DUNS                        = 'duns' ;
    const string EMAIL                       = 'email' ;
    const string FAMILY_NAME                 = 'familyName' ;
    const string FAX_NUMBER                  = 'faxNumber' ;
    const string FOLLOWS                     = 'follows' ;
    const string FUNDER                      = 'funder' ;
    const string FUNDING                     = 'funding' ;
    const string GENDER                      = 'gender' ;
    const string GIVEN_NAME                  = 'givenName' ;
    const string GLOBAL_LOCATION_NUMBER      = 'globalLocationNumber' ;
    const string HAS_CERTIFICATION           = 'hasCertification' ;
    const string HAS_CREDENTIAL              = 'hasCredential' ;
    const string HAS_OCCUPATION              = 'hasOccupation' ;
    const string HAS_OFFER_CATALOG           = 'hasOfferCatalog' ;
    const string HAS_POS                     = 'hasPOS' ;
    const string HEIGHT                      = 'height' ;
    const string HOME_LOCATION               = 'homeLocation' ;
    const string HONORIFIC_PREFIX            = 'honorificPrefix' ;
    const string HONORIFIC_SUFFIX            = 'honorificSuffix' ;
    const string INTERACTIONS_STATISTIC      = 'interactionStatistic' ;
    const string ISIC_V4                     = 'isicV4' ;
    const string JOB_TITLE                   = 'jobTitle' ;
    const string KNOWS                       = 'knows' ;
    const string KNOWS_ABOUT                 = 'knowsAbout' ;
    const string KNOWS_LANGUAGE              = 'knowsLanguage' ;
    const string LOGO                        = 'logo' ;
    const string MAKES_OFFER                 = 'makesOffer' ;
    const string MEMBER_OF                   = 'memberOf' ;
    const string NAICS                       = 'naics' ;
    const string NATIONALITY                 = 'nationality' ;
    const string NET_WORTH                   = 'netWorth' ;
    const string OWNS                        = 'owns' ;
    const string PARENT                      = 'parent' ;
    const string PERFORMER_IN                = 'performerIn' ;
    const string PRONOUNS                    = 'pronouns' ;
    const string PUBLISHING_PRINCIPLES       = 'publishingPrinciples' ;
    const string RELATED_TO                  = 'relatedTo' ;
    const string SEEKS                       = 'seeks' ;
    const string SIBLING                     = 'sibling' ;
    const string SKILLS                      = 'skills' ;
    const string SPONSOR                     = 'sponsor' ;
    const string SPOUSE                      = 'spouse' ;
    const string TAX_ID                      = 'taxID' ;
    const string VAT_ID                      = 'vatID' ;
    const string WEIGHT                      = 'weight' ;
    const string WORK_LOCATION               = 'workLocation' ;
    const string WORKS_FOR                   = 'worksFor' ;
}