<?php

namespace org\schema\constants\traits;

/**
 * Enumeration of all properties defines in the schema.org and custom ontologies.
 */
trait Properties
{
    use Action ,
        AggregateOffer ,
        AggregateRating ,
        AlignmentObject ,
        Audience ,
        Brand ,
        CategoryCode ,
        Claim ,
        Common ,
        ConceptualObject ,
        CompoundPriceSpecification ,
        ConstraintNode ,
        ContactPoint ,
        ContactType ,
        CreativeWork ,
        DataFeedItem ,
        Dataset ,
        DefinedRegion ,
        DefinedTerm ,
        DefinedTermSet ,
        DeliveryChargeSpecification ,
        Demand ,
        DublinCore ,
        EndorsementRating ,
        EntryPoint ,
        Enumeration ,
        Edge ,
        EducationalOccupationCredential ,
        Event ,
        FinancialIncentive ,
        GeoCircle ,
        GeoCoordinates ,
        GeospatialGeometry ,
        GeoShape ,
        Grant ,
        HoursSpecification ,
        I18n ,
        InteractionCounter ,
        Invoice ,
        ItemList ,
        Keyword ,
        ListItem ,
        LocationFeatureSpecification ,
        Measurement ,
        MemberProgram ,
        MemberProgramTier ,
        MediaObject ,
        Medias ,
        MediaSubscription ,
        Order ,
        Offer ,
        OfferShippingDetails ,
        Organization ,
        Person ,
        Place ,
        PostalAddress ,
        PriceSpecification ,
        Product ,
        ProductGroup ,
        ProductModel ,
        Rating ,
        Review ,
        Service ,
        ShippingService ,
        Thing  ,
        UnitPriceSpecification ,
        Values ,
        WebAPI
        ;
}