<?php

namespace org\schema\constants\traits;

/**
 * Enumeration of all properties defines in the schema.org and custom ontologies.
 */
trait Properties
{
    use Action ,
        AggregateOffer ,
        AggregateRating ,
        AlignmentObject ,
        ArangoDB ,
        Audience ,
        Brand ,
        CategoryCode ,
        Claim ,
        Common ,
        CompoundPriceSpecification ,
        ConceptualObject ,
        ConstraintNode ,
        ContactPoint ,
        CreativeWork ,
        Credential ,
        DataFeedItem ,
        Dataset ,
        DefinedRegion ,
        DefinedTerm ,
        DefinedTermSet ,
        DeliveryChargeSpecification ,
        DeliveryEvent ,
        Demand ,
        DublinCore ,
        EducationalOccupationCredential ,
        EndorsementRating ,
        EntryPoint ,
        Enumeration ,
        Event ,
        FinancialIncentive ,
        FlightReservation ,
        FoodEstablishmentReservation ,
        GeoCircle ,
        GeoCoordinates ,
        GeoShape ,
        GeospatialGeometry ,
        Grant ,
        HoursSpecification ,
        I18n ,
        InteractionCounter ,
        Invoice ,
        ItemList ,
        Keyword ,
        ListItem ,
        LocationFeatureSpecification ,
        LodgingReservation ,
        Measurement ,
        MediaObject ,
        Medias ,
        MediaSubscription ,
        MemberProgram ,
        MemberProgramTier ,
        MonetaryAmount ,
        Occupation ,
        OccupationExperienceRequirements ,
        Offer ,
        OfferShippingDetails ,
        Order ,
        OrderItem ,
        Organization ,
        OwnershipInfo ,
        ParcelDelivery ,
        PaymentMethod ,
        Permit ,
        Person ,
        Place ,
        PostalAddress ,
        PostalCodeRangeSpecification ,
        PriceSpecification ,
        Product ,
        ProductCollection ,
        ProductGroup ,
        ProductModel ,
        ProgramMembership ,
        Property ,
        QualitativeValue ,
        Rating ,
        RentalCarReservation ,
        RepaymentSpecification ,
        Reservation ,
        ReservationPackage ,
        Review ,
        Schedule ,
        Seat ,
        Service ,
        ServiceChannel ,
        ServicePeriod ,
        ShippingConditions ,
        ShippingDeliveryTime ,
        ShippingRateSettings ,
        ShippingService ,
        SizeSpecification ,
        StatisticalVariable ,
        TaxiReservation ,
        Taxon ,
        Thing ,
        Ticket ,
        TypeAndQuantityNode ,
        UnitPriceSpecification ,
        Values ,
        WebAPI
        ;
}