<?php

namespace org\schema;

use org\schema\creativeWork\Certification;
use org\schema\creativeWork\medias\ImageObject;
use org\schema\places\AdministrativeArea;

/**
 * A service provided by an organization, e.g. delivery service, print services, etc.
 * @see https://schema.org/Service
 */
class Service extends Intangible
{
    /**
     * The overall rating, based on a collection of reviews or ratings, of the item.
     * @var array|AggregateRating|null
     */
    public null|array|AggregateRating $aggregateRating ;

    /**
     * The geographic area where a service or offered item is provided.
     * @var null|string|Place|GeoShape|AdministrativeArea|array
     */
    public null|string|Place|GeoShape|AdministrativeArea|array $areaServed ;

    /**
     * An intended audience, i.e. a group for whom something was created. Supersedes serviceAudience.
     * @var array|Audience|null
     */
    public null|array|Audience $audience ;

    /**
     * A means of accessing the service (e.g. a phone bank, a web site, a location, etc.).
     * @var ServiceChannel|null
     */
    public null|ServiceChannel $availableChannel ;

    /**
     * An award won by or for this item.
     * @var string|array|null
     */
    public null|string|array $award ;

    /**
     * The brand(s) associated with a product or service, or the brand(s) maintained by an organization or business person.
     * @var Brand|Organization|array|null
     */
    public Brand|Organization|array|null $brand ;

    /**
     * An entity that arranges for an exchange between a buyer and a seller.
     * In most cases a broker never acquires or releases ownership of a product or service involved in an exchange.
     * If it is not clear whether an entity is a broker, seller, or buyer, the latter two terms are preferred.
     * @var Person|Organization|null
     */
    public Person|Organization|null $broker ;

    /**
     * A category for the item. Greater signs or slashes can be used to informally indicate a category hierarchy.
     * @var null|array|string|CategoryCode|Thing
     */
    public null|array|string|CategoryCode|Thing $category = null ;

    /**
     * Certification information about a product, organization, service, place, or person.
     * @var array|Certification|null
     */
    public null|array|Certification $hasCertification ;

    /**
     * Indicates an OfferCatalog listing for this Organization, Person, or Service.
     * @var array|OfferCatalog|null
     */
    public null|array|OfferCatalog $hasOfferCatalog ;

    /**
     * The hours during which this service or contact is available.
     * @var OpeningHoursSpecification|null
     */
    public null|OpeningHoursSpecification $hoursAvailable ;

    /**
     * A pointer to another, somehow related product (or multiple products).
     * @var Product|Service|array|null
     */
    public null|Product|Service|array $isRelatedTo ;

    /**
     * A pointer to another, functionally similar product (or multiple products).
     * @var Product|Service|array|null
     */
    public null|Product|Service|array $isSimilarTo ;

    /**
     * An associated logo.
     * @var string|ImageObject|null
     */
    public null|string|ImageObject $logo ;

    /**
     * An offer to provide this item.
     * @var array|Offer|Demand|null
     */
    public array|Offer|Demand|null $offers ;

    /**
     * The service provider, service operator, or service performer; the goods producer.
     * Another party (a seller) may offer those services or goods on behalf of the provider.
     * A provider may also serve as the seller.
     * @var Person|Organization|null
     */
    public Person|Organization|null $provider ;

    /**
     * Indicates the mobility of a provided service (e.g. 'static', 'dynamic').
     * @var string|null
     */
    public ?string $providerMobility ;

    /**
     * A review of the item.
     * @var array|Review|null
     */
    public null|array|Review $review ;

    /**
     * The tangible thing generated by the service, e.g. a passport, permit, etc.
     * @var Thing|null
     */
    public ?Thing $serviceOutput ;

    /**
     * The type of service being offered, e.g. veterans' benefits, emergency relief, etc.
     * @var string|Enumeration|DefinedTerm|null
     */
    public null|string|Enumeration|DefinedTerm $serviceType ;

    /**
     * A slogan or motto associated with the item.
     * @var string|null
     */
    public ?string $slogan ;

    /**
     * Human-readable terms of service documentation.
     * @var string|null|object
     */
    public null|object|string $termsOfService;
}